#!/usr/bin/env python3
"""
save_planned_traj.py
Suscribe a un topic moveit_msgs/DisplayTrajectory y salva las trayectorias planeadas
en formatos: py, json, csv, txt.

Ejemplos:
  ./save_planned_traj.py
  ./save_planned_traj.py --topic /move_group/display_planned_path --out /tmp/traj.py --format py --once
  ./save_planned_traj.py -t /display_planned_path -f json

Requisitos: tener ROS2 Humble (rclpy), y los paquetes de mensajes moveit_msgs instalados y en PYTHONPATH.
"""
import rclpy
from rclpy.node import Node
from moveit_msgs.msg import DisplayTrajectory
import argparse
import json
import time
from datetime import datetime
import os
import csv

def make_timestamp():
    return datetime.now().strftime("%Y%m%d_%H%M%S")

class PlannedTrajectorySaver(Node):
    def __init__(self, topic, out_dir, fmt, once):
        super().__init__("planned_traj_saver")
        self.topic = topic
        self.out_dir = out_dir
        self.fmt = fmt.lower()
        self.once = once

        # crear carpeta de salida si no existe
        os.makedirs(self.out_dir, exist_ok=True)

        self.sub = self.create_subscription(
            DisplayTrajectory,
            self.topic,
            self.callback,
            10
        )
        self.get_logger().info(f"Subscribed to '{self.topic}', saving to '{self.out_dir}' (format: {self.fmt})")

    def callback(self, msg: DisplayTrajectory):
        # msg.trajectory es una lista de RobotTrajectory (cada uno tiene joint_trajectory)
        if not msg.trajectory:
            self.get_logger().warning("Se recibió DisplayTrajectory pero .trajectory está vacío.")
            return

        ts = make_timestamp()
        saved_files = []

        # Hay casos con múltiples trajectories en un solo mensaje; los manejamos todos
        for idx, robot_traj in enumerate(msg.trajectory):
            jt = getattr(robot_traj, "joint_trajectory", None)
            if jt is None:
                self.get_logger().warning(f"Trajectory {idx} no tiene joint_trajectory. Saltando.")
                continue

            joint_names = list(jt.joint_names)
            # construir lista de waypoints: lista de listas (positions)
            waypoints = []
            for p in jt.points:
                # p.positions es una lista de floats; si está vacía, saltar
                if not p.positions:
                    continue
                waypoints.append(list(p.positions))

            if not waypoints:
                self.get_logger().warning(f"Trajectory {idx} no tenía puntos con positions. Saltando.")
                continue

            base_name = f"planned_traj_{ts}_traj{idx}"
            out_path = os.path.join(self.out_dir, base_name + {
                "py": ".py", "json": ".json", "csv": ".csv", "txt": ".txt"
            }[self.fmt])

            # Guardar según formato
            if self.fmt == "py":
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write("# Generated by save_planned_traj.py\n")
                    f.write(f"# topic: {self.topic}\n")
                    f.write(f"joint_names = {json.dumps(joint_names, indent=2)}\n\n")
                    f.write("trajectory = [\n")
                    for wp in waypoints:
                        f.write("    " + json.dumps(wp) + ",\n")
                    f.write("]\n")
                saved_files.append(out_path)

            elif self.fmt == "json":
                payload = {"topic": self.topic, "joint_names": joint_names, "trajectory": waypoints}
                with open(out_path, "w", encoding="utf-8") as f:
                    json.dump(payload, f, indent=2)
                saved_files.append(out_path)

            elif self.fmt == "csv":
                # csv: header = joint_names, then rows per waypoint
                with open(out_path, "w", newline='', encoding="utf-8") as f:
                    writer = csv.writer(f)
                    writer.writerow(joint_names)
                    for wp in waypoints:
                        writer.writerow(wp)
                saved_files.append(out_path)

            elif self.fmt == "txt":
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write("# topic: " + self.topic + "\n")
                    f.write("# joint_names: " + ", ".join(joint_names) + "\n")
                    for wp in waypoints:
                        f.write(",".join([str(x) for x in wp]) + "\n")
                saved_files.append(out_path)

            else:
                self.get_logger().error(f"Formato no soportado: {self.fmt}")
                return

            self.get_logger().info(f"Guardado trajectory {idx} -> {out_path}  (waypoints: {len(waypoints)})")

        if saved_files and self.once:
            self.get_logger().info("Modo --once: saliendo después de la primera publicación guardada.")
            # permitir que se envíen logs antes de apagar
            time.sleep(0.15)
            rclpy.shutdown()

def main():
    parser = argparse.ArgumentParser(description="Save MoveIt planned trajectory (DisplayTrajectory) to file.")
    parser.add_argument("-t", "--topic", default="/display_planned_path",
                        help="Topic to subscribe (default /display_planned_path). You may want /move_group/display_planned_path.")
    parser.add_argument("-o", "--out", default=".",
                        help="Output directory (default current dir).")
    parser.add_argument("-f", "--format", choices=["py","json","csv","txt"], default="py",
                        help="Output format (py/json/csv/txt). Default: py")
    parser.add_argument("--once", action="store_true", help="Save the first received publication and exit.")
    args = parser.parse_args()

    # iniciar rclpy
    rclpy.init()
    node = PlannedTrajectorySaver(args.topic, args.out, args.format, args.once)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == "__main__":
    main()
